baseURL = 'https://bellshun.github.io'
languageCode = 'ja-jp'
title = 'ポートフォリオまとめ'
theme = 'github-style'
defaultContentLanguage = "ja"
copyright = "Copyright © 2022 bellshun"
summarylength = 60
HasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodefences = true 

[params]
  author = "bellshun"
  description = "趣味で作成したものを掲載します"
  github = "bellshun"
  twitter = "bellshun_9973"
  url = "https://note.com/memomemotarou"
  keywords = "blog, google analytics"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "Saitama/Tokyo"
  enableGitalk = false